// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// draw_posterior_hazard_samples_cpp
arma::mat draw_posterior_hazard_samples_cpp(int num_intervals, const arma::ivec& events_per_interval, const arma::vec& person_time_per_interval, const arma::vec& prior_alpha_params, const arma::vec& prior_beta_params, int num_samples);
RcppExport SEXP _evolveTrial_draw_posterior_hazard_samples_cpp(SEXP num_intervalsSEXP, SEXP events_per_intervalSEXP, SEXP person_time_per_intervalSEXP, SEXP prior_alpha_paramsSEXP, SEXP prior_beta_paramsSEXP, SEXP num_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_intervals(num_intervalsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type events_per_interval(events_per_intervalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type person_time_per_interval(person_time_per_intervalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prior_alpha_params(prior_alpha_paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prior_beta_params(prior_beta_paramsSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_posterior_hazard_samples_cpp(num_intervals, events_per_interval, person_time_per_interval, prior_alpha_params, prior_beta_params, num_samples));
    return rcpp_result_gen;
END_RCPP
}
// calculate_median_survival_piecewise_cpp
double calculate_median_survival_piecewise_cpp(const arma::vec& hazard_rates, const arma::vec& interval_lengths);
RcppExport SEXP _evolveTrial_calculate_median_survival_piecewise_cpp(SEXP hazard_ratesSEXP, SEXP interval_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type hazard_rates(hazard_ratesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type interval_lengths(interval_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_median_survival_piecewise_cpp(hazard_rates, interval_lengths));
    return rcpp_result_gen;
END_RCPP
}
// calculate_median_survival_matrix_cpp
arma::vec calculate_median_survival_matrix_cpp(const arma::mat& hazard_samples, const arma::vec& interval_lengths);
RcppExport SEXP _evolveTrial_calculate_median_survival_matrix_cpp(SEXP hazard_samplesSEXP, SEXP interval_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type hazard_samples(hazard_samplesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type interval_lengths(interval_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_median_survival_matrix_cpp(hazard_samples, interval_lengths));
    return rcpp_result_gen;
END_RCPP
}
// ph_beta_mode_var_cpp
List ph_beta_mode_var_cpp(const arma::ivec& E_C, const arma::vec& PT_C, const arma::ivec& E_T, const arma::vec& PT_T, const arma::vec& alpha_prior, const arma::vec& beta_prior, double mu, double sigma, double tol, int max_iter);
RcppExport SEXP _evolveTrial_ph_beta_mode_var_cpp(SEXP E_CSEXP, SEXP PT_CSEXP, SEXP E_TSEXP, SEXP PT_TSEXP, SEXP alpha_priorSEXP, SEXP beta_priorSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type E_C(E_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PT_C(PT_CSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type E_T(E_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PT_T(PT_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_prior(alpha_priorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_prior(beta_priorSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(ph_beta_mode_var_cpp(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, mu, sigma, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// sample_vs_ref_medians_ph_cpp
List sample_vs_ref_medians_ph_cpp(const arma::ivec& E_C, const arma::vec& PT_C, const arma::ivec& E_T, const arma::vec& PT_T, const arma::vec& alpha_prior, const arma::vec& beta_prior, const arma::vec& interval_lengths, double mu, double sigma, int num_samples);
RcppExport SEXP _evolveTrial_sample_vs_ref_medians_ph_cpp(SEXP E_CSEXP, SEXP PT_CSEXP, SEXP E_TSEXP, SEXP PT_TSEXP, SEXP alpha_priorSEXP, SEXP beta_priorSEXP, SEXP interval_lengthsSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP num_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type E_C(E_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PT_C(PT_CSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type E_T(E_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PT_T(PT_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_prior(alpha_priorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_prior(beta_priorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type interval_lengths(interval_lengthsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_vs_ref_medians_ph_cpp(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, mu, sigma, num_samples));
    return rcpp_result_gen;
END_RCPP
}
// sample_vs_ref_medians_independent_cpp
List sample_vs_ref_medians_independent_cpp(const arma::ivec& E_C, const arma::vec& PT_C, const arma::ivec& E_T, const arma::vec& PT_T, const arma::vec& alpha_prior, const arma::vec& beta_prior, const arma::vec& interval_lengths, int num_samples);
RcppExport SEXP _evolveTrial_sample_vs_ref_medians_independent_cpp(SEXP E_CSEXP, SEXP PT_CSEXP, SEXP E_TSEXP, SEXP PT_TSEXP, SEXP alpha_priorSEXP, SEXP beta_priorSEXP, SEXP interval_lengthsSEXP, SEXP num_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type E_C(E_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PT_C(PT_CSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type E_T(E_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PT_T(PT_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha_prior(alpha_priorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_prior(beta_priorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type interval_lengths(interval_lengthsSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_vs_ref_medians_independent_cpp(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, num_samples));
    return rcpp_result_gen;
END_RCPP
}
// test_rcpp_sum
double test_rcpp_sum(const arma::vec& x);
RcppExport SEXP _evolveTrial_test_rcpp_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(test_rcpp_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// test_armadillo_random
double test_armadillo_random(int n);
RcppExport SEXP _evolveTrial_test_armadillo_random(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_armadillo_random(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_evolveTrial_draw_posterior_hazard_samples_cpp", (DL_FUNC) &_evolveTrial_draw_posterior_hazard_samples_cpp, 6},
    {"_evolveTrial_calculate_median_survival_piecewise_cpp", (DL_FUNC) &_evolveTrial_calculate_median_survival_piecewise_cpp, 2},
    {"_evolveTrial_calculate_median_survival_matrix_cpp", (DL_FUNC) &_evolveTrial_calculate_median_survival_matrix_cpp, 2},
    {"_evolveTrial_ph_beta_mode_var_cpp", (DL_FUNC) &_evolveTrial_ph_beta_mode_var_cpp, 10},
    {"_evolveTrial_sample_vs_ref_medians_ph_cpp", (DL_FUNC) &_evolveTrial_sample_vs_ref_medians_ph_cpp, 10},
    {"_evolveTrial_sample_vs_ref_medians_independent_cpp", (DL_FUNC) &_evolveTrial_sample_vs_ref_medians_independent_cpp, 8},
    {"_evolveTrial_test_rcpp_sum", (DL_FUNC) &_evolveTrial_test_rcpp_sum, 1},
    {"_evolveTrial_test_armadillo_random", (DL_FUNC) &_evolveTrial_test_armadillo_random, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_evolveTrial(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
