# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate a single hybrid trial (C++ implementation)
#'
#' @param theta_list List of design parameters
#' @param base_args_list List of base trial configuration
#' @param scenario_params_list List of scenario parameters
#' @return List with trial results
#' @export
simulate_hybrid_trial_cpp <- function(theta_list, base_args_list, scenario_params_list) {
    .Call(`_evolveTrial_simulate_hybrid_trial_cpp`, theta_list, base_args_list, scenario_params_list)
}

#' Run multiple hybrid trial simulations (C++ implementation)
#'
#' @param n_sim Number of simulations
#' @param theta_list Design parameters
#' @param base_args_list Base configuration
#' @param scenario_params_list Scenario parameters
#' @return Data frame with simulation results
#' @export
run_hybrid_simulations_cpp <- function(n_sim, theta_list, base_args_list, scenario_params_list) {
    .Call(`_evolveTrial_run_hybrid_simulations_cpp`, n_sim, theta_list, base_args_list, scenario_params_list)
}

#' Compute hybrid trial operating characteristics (C++ implementation)
#'
#' @param n_sim Number of simulations
#' @param theta_list Design parameters
#' @param base_args_list Base configuration
#' @param scenario_params_list Scenario parameters (alternative hypothesis)
#' @param null_scenario_list Scenario parameters (null hypothesis)
#' @return List with power, type1, EN, conversion rate (including per-arm metrics)
#' @export
compute_hybrid_oc_cpp <- function(n_sim, theta_list, base_args_list, scenario_params_list, null_scenario_list) {
    .Call(`_evolveTrial_compute_hybrid_oc_cpp`, n_sim, theta_list, base_args_list, scenario_params_list, null_scenario_list)
}

#' Draw posterior hazard samples (C++ implementation)
#'
#' Draws samples from the posterior distribution of hazard rates for each interval
#' in a Bayesian piecewise exponential model with Gamma priors.
#'
#' @param num_intervals Number of intervals in piecewise model
#' @param events_per_interval Integer vector of observed events per interval
#' @param person_time_per_interval Numeric vector of person-time at risk per interval
#' @param prior_alpha_params Numeric vector of Gamma prior shape parameters
#' @param prior_beta_params Numeric vector of Gamma prior rate parameters
#' @param num_samples Number of posterior samples to draw
#' @return Matrix with num_samples rows and num_intervals columns of hazard samples
#' @export
draw_posterior_hazard_samples_cpp <- function(num_intervals, events_per_interval, person_time_per_interval, prior_alpha_params, prior_beta_params, num_samples) {
    .Call(`_evolveTrial_draw_posterior_hazard_samples_cpp`, num_intervals, events_per_interval, person_time_per_interval, prior_alpha_params, prior_beta_params, num_samples)
}

#' Calculate median survival for piecewise exponential model (C++ implementation)
#'
#' Computes the median survival time for a piecewise exponential model.
#' If the 0.5 survival is not reached by the end of the last interval,
#' continues past the last cutpoint with the last interval's hazard (open-ended tail).
#' Only returns Inf if the last hazard is exactly zero.
#'
#' @param hazard_rates Numeric vector of hazard rates for each interval
#' @param interval_lengths Numeric vector of interval lengths (durations)
#' @return Median survival time (numeric scalar, possibly Inf)
#' @export
calculate_median_survival_piecewise_cpp <- function(hazard_rates, interval_lengths) {
    .Call(`_evolveTrial_calculate_median_survival_piecewise_cpp`, hazard_rates, interval_lengths)
}

#' Calculate median survival for multiple hazard samples (C++ implementation)
#'
#' Vectorized version that processes an entire matrix of posterior hazard samples.
#' Each row is a posterior sample; each column is an interval.
#'
#' @param hazard_samples Matrix with num_samples rows and num_intervals columns
#' @param interval_lengths Numeric vector of interval lengths (durations)
#' @return Numeric vector of median survival times (length num_samples)
#' @export
calculate_median_survival_matrix_cpp <- function(hazard_samples, interval_lengths) {
    .Call(`_evolveTrial_calculate_median_survival_matrix_cpp`, hazard_samples, interval_lengths)
}

#' Compute mode and variance of log-HR posterior for PH model (C++ implementation)
#'
#' Uses Newton-Raphson iteration to find the mode of the log-HR posterior
#' under a proportional hazards model with Gamma prior on baseline hazards
#' and normal prior on log-HR.
#'
#' @param E_C Integer vector of control events per interval
#' @param PT_C Numeric vector of control person-time per interval
#' @param E_T Integer vector of treatment events per interval
#' @param PT_T Numeric vector of treatment person-time per interval
#' @param alpha_prior Numeric vector of Gamma prior shape parameters
#' @param beta_prior Numeric vector of Gamma prior rate parameters
#' @param mu Log-HR prior mean
#' @param sigma Log-HR prior SD
#' @param tol Convergence tolerance (default 1e-6)
#' @param max_iter Maximum Newton-Raphson iterations (default 50)
#' @return List with "mean" and "sd" of log-HR posterior
#' @export
ph_beta_mode_var_cpp <- function(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, mu, sigma, tol = 1e-6, max_iter = 50L) {
    .Call(`_evolveTrial_ph_beta_mode_var_cpp`, E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, mu, sigma, tol, max_iter)
}

#' Sample medians for vs-ref PH model (C++ implementation)
#'
#' End-to-end posterior sampler for proportional hazards model.
#' Samples log-HR from posterior, then baseline hazards, then computes medians.
#'
#' @param E_C Integer vector of control events per interval
#' @param PT_C Numeric vector of control person-time per interval
#' @param E_T Integer vector of treatment events per interval
#' @param PT_T Numeric vector of treatment person-time per interval
#' @param alpha_prior Numeric vector of Gamma prior shape parameters
#' @param beta_prior Numeric vector of Gamma prior rate parameters
#' @param interval_lengths Numeric vector of interval durations
#' @param mu Log-HR prior mean
#' @param sigma Log-HR prior SD
#' @param num_samples Number of posterior samples
#' @return List with "medCtrl", "medTrt", and "logHR" vectors
#' @export
sample_vs_ref_medians_ph_cpp <- function(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, mu, sigma, num_samples) {
    .Call(`_evolveTrial_sample_vs_ref_medians_ph_cpp`, E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, mu, sigma, num_samples)
}

#' Sample medians for vs-ref independent model (C++ implementation)
#'
#' End-to-end posterior sampler for independent hazards model.
#' Used for single-arm trials and multi-arm trials with independent hazards.
#'
#' @param E_C Integer vector of control events per interval
#' @param PT_C Numeric vector of control person-time per interval
#' @param E_T Integer vector of treatment events per interval
#' @param PT_T Numeric vector of treatment person-time per interval
#' @param alpha_prior Numeric vector of Gamma prior shape parameters
#' @param beta_prior Numeric vector of Gamma prior rate parameters
#' @param interval_lengths Numeric vector of interval durations
#' @param num_samples Number of posterior samples
#' @return List with "medCtrl" and "medTrt" vectors (no logHR for independent model)
#' @export
sample_vs_ref_medians_independent_cpp <- function(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, num_samples) {
    .Call(`_evolveTrial_sample_vs_ref_medians_independent_cpp`, E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, num_samples)
}

#' Simulate PWE survival times (C++ vectorized)
#'
#' @param n Number of survival times to simulate
#' @param lambda Hazard rates per interval
#' @param interval_cutpoints Interval boundaries (length = n_intervals + 1)
#' @return Vector of n survival times
#' @export
simulate_pwe_survival_batch_cpp <- function(n, lambda, interval_cutpoints) {
    .Call(`_evolveTrial_simulate_pwe_survival_batch_cpp`, n, lambda, interval_cutpoints)
}

#' Simulate future arm data under PWE model (C++)
#'
#' @param n_patients Number of future patients
#' @param lambda Hazard rates per interval
#' @param interval_cutpoints Interval boundaries
#' @param accrual_rate Patients per time unit
#' @param followup Follow-up time after enrollment complete
#' @return List with events and exposure vectors
#' @export
simulate_future_arm_pwe_cpp <- function(n_patients, lambda, interval_cutpoints, accrual_rate, followup) {
    .Call(`_evolveTrial_simulate_future_arm_pwe_cpp`, n_patients, lambda, interval_cutpoints, accrual_rate, followup)
}

#' Compute between-arm posterior probability (C++)
#'
#' @param a_exp Posterior shape for experimental arm
#' @param b_exp Posterior rate for experimental arm
#' @param a_ref Posterior shape for reference arm
#' @param b_ref Posterior rate for reference arm
#' @return P(HR < 1 | data)
#' @export
compute_ba_posterior_cpp <- function(a_exp, b_exp, a_ref, b_ref) {
    .Call(`_evolveTrial_compute_ba_posterior_cpp`, a_exp, b_exp, a_ref, b_ref)
}

#' Compute predictive probability for hybrid trial conversion (C++)
#'
#' Full Monte Carlo computation with optional antithetic variates and early stopping.
#'
#' @param a_exp Current posterior shape for experimental arm (per interval)
#' @param b_exp Current posterior rate for experimental arm (per interval)
#' @param a_ref Current posterior shape for reference arm (per interval)
#' @param b_ref Current posterior rate for reference arm (per interval)
#' @param n_add Number of additional patients to simulate per arm
#' @param interval_cutpoints PWE interval boundaries
#' @param accrual_rate Patients per time unit
#' @param followup Follow-up time after enrollment
#' @param eff_ba Efficacy threshold for BA decision
#' @param pp_go PP threshold for GO decision
#' @param pp_nogo PP threshold for NO-GO decision
#' @param n_outer Number of outer MC samples
#' @param use_antithetic Use antithetic variates for variance reduction
#' @param use_early_stop Enable early stopping based on CI
#' @return Predictive probability of success
#' @export
compute_pp_predictive_cpp <- function(a_exp, b_exp, a_ref, b_ref, n_add, interval_cutpoints, accrual_rate, followup, eff_ba, pp_go, pp_nogo, n_outer = 500L, use_antithetic = TRUE, use_early_stop = TRUE) {
    .Call(`_evolveTrial_compute_pp_predictive_cpp`, a_exp, b_exp, a_ref, b_ref, n_add, interval_cutpoints, accrual_rate, followup, eff_ba, pp_go, pp_nogo, n_outer, use_antithetic, use_early_stop)
}

#' Compute predictive probability for single-arm efficacy (C++)
#'
#' Monte Carlo computation of PP that single arm will reach efficacy threshold
#' vs historical control at the final analysis.
#'
#' @param a_arm Current posterior shape for arm (per interval)
#' @param b_arm Current posterior rate for arm (per interval)
#' @param hist_hazard Historical hazard rates (per interval)
#' @param hr_threshold Hazard ratio threshold for efficacy
#' @param n_add Number of additional patients to simulate
#' @param interval_cutpoints PWE interval boundaries
#' @param accrual_rate Patients per time unit
#' @param followup Follow-up time after enrollment
#' @param eff_threshold Efficacy posterior threshold (e.g., 0.90)
#' @param n_outer Number of outer MC samples
#' @param use_antithetic Use antithetic variates for variance reduction
#' @return Predictive probability of reaching efficacy
#' @export
compute_pp_efficacy_sa_cpp <- function(a_arm, b_arm, hist_hazard, hr_threshold, n_add, interval_cutpoints, accrual_rate, followup, eff_threshold, n_outer = 200L, use_antithetic = TRUE) {
    .Call(`_evolveTrial_compute_pp_efficacy_sa_cpp`, a_arm, b_arm, hist_hazard, hr_threshold, n_add, interval_cutpoints, accrual_rate, followup, eff_threshold, n_outer, use_antithetic)
}

#' Compute predictive probability for single-arm futility (C++)
#'
#' Monte Carlo computation of PP that single arm will trigger futility
#' vs historical control at the final analysis.
#'
#' @param a_arm Current posterior shape for arm (per interval)
#' @param b_arm Current posterior rate for arm (per interval)
#' @param hist_hazard Historical hazard rates (per interval)
#' @param hr_threshold Hazard ratio threshold for efficacy
#' @param n_add Number of additional patients to simulate
#' @param interval_cutpoints PWE interval boundaries
#' @param accrual_rate Patients per time unit
#' @param followup Follow-up time after enrollment
#' @param fut_threshold Futility posterior threshold (e.g., 0.10)
#' @param n_outer Number of outer MC samples
#' @param use_antithetic Use antithetic variates for variance reduction
#' @return Predictive probability of triggering futility
#' @export
compute_pp_futility_sa_cpp <- function(a_arm, b_arm, hist_hazard, hr_threshold, n_add, interval_cutpoints, accrual_rate, followup, fut_threshold, n_outer = 200L, use_antithetic = TRUE) {
    .Call(`_evolveTrial_compute_pp_futility_sa_cpp`, a_arm, b_arm, hist_hazard, hr_threshold, n_add, interval_cutpoints, accrual_rate, followup, fut_threshold, n_outer, use_antithetic)
}

#' Test Rcpp setup
#'
#' Simple test function to verify Rcpp and RcppArmadillo are working.
#'
#' @param x A numeric vector
#' @return Sum of the vector
#' @export
test_rcpp_sum <- function(x) {
    .Call(`_evolveTrial_test_rcpp_sum`, x)
}

#' Test Armadillo matrix operations
#'
#' @param n Matrix dimension
#' @return Mean of random normal matrix
#' @export
test_armadillo_random <- function(n) {
    .Call(`_evolveTrial_test_armadillo_random`, n)
}

