# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw posterior hazard samples (C++ implementation)
#'
#' Draws samples from the posterior distribution of hazard rates for each interval
#' in a Bayesian piecewise exponential model with Gamma priors.
#'
#' @param num_intervals Number of intervals in piecewise model
#' @param events_per_interval Integer vector of observed events per interval
#' @param person_time_per_interval Numeric vector of person-time at risk per interval
#' @param prior_alpha_params Numeric vector of Gamma prior shape parameters
#' @param prior_beta_params Numeric vector of Gamma prior rate parameters
#' @param num_samples Number of posterior samples to draw
#' @return Matrix with num_samples rows and num_intervals columns of hazard samples
#' @export
draw_posterior_hazard_samples_cpp <- function(num_intervals, events_per_interval, person_time_per_interval, prior_alpha_params, prior_beta_params, num_samples) {
    .Call(`_evolveTrial_draw_posterior_hazard_samples_cpp`, num_intervals, events_per_interval, person_time_per_interval, prior_alpha_params, prior_beta_params, num_samples)
}

#' Calculate median survival for piecewise exponential model (C++ implementation)
#'
#' Computes the median survival time for a piecewise exponential model.
#' If the 0.5 survival is not reached by the end of the last interval,
#' continues past the last cutpoint with the last interval's hazard (open-ended tail).
#' Only returns Inf if the last hazard is exactly zero.
#'
#' @param hazard_rates Numeric vector of hazard rates for each interval
#' @param interval_lengths Numeric vector of interval lengths (durations)
#' @return Median survival time (numeric scalar, possibly Inf)
#' @export
calculate_median_survival_piecewise_cpp <- function(hazard_rates, interval_lengths) {
    .Call(`_evolveTrial_calculate_median_survival_piecewise_cpp`, hazard_rates, interval_lengths)
}

#' Calculate median survival for multiple hazard samples (C++ implementation)
#'
#' Vectorized version that processes an entire matrix of posterior hazard samples.
#' Each row is a posterior sample; each column is an interval.
#'
#' @param hazard_samples Matrix with num_samples rows and num_intervals columns
#' @param interval_lengths Numeric vector of interval lengths (durations)
#' @return Numeric vector of median survival times (length num_samples)
#' @export
calculate_median_survival_matrix_cpp <- function(hazard_samples, interval_lengths) {
    .Call(`_evolveTrial_calculate_median_survival_matrix_cpp`, hazard_samples, interval_lengths)
}

#' Compute mode and variance of log-HR posterior for PH model (C++ implementation)
#'
#' Uses Newton-Raphson iteration to find the mode of the log-HR posterior
#' under a proportional hazards model with Gamma prior on baseline hazards
#' and normal prior on log-HR.
#'
#' @param E_C Integer vector of control events per interval
#' @param PT_C Numeric vector of control person-time per interval
#' @param E_T Integer vector of treatment events per interval
#' @param PT_T Numeric vector of treatment person-time per interval
#' @param alpha_prior Numeric vector of Gamma prior shape parameters
#' @param beta_prior Numeric vector of Gamma prior rate parameters
#' @param mu Log-HR prior mean
#' @param sigma Log-HR prior SD
#' @param tol Convergence tolerance (default 1e-6)
#' @param max_iter Maximum Newton-Raphson iterations (default 50)
#' @return List with "mean" and "sd" of log-HR posterior
#' @export
ph_beta_mode_var_cpp <- function(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, mu, sigma, tol = 1e-6, max_iter = 50L) {
    .Call(`_evolveTrial_ph_beta_mode_var_cpp`, E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, mu, sigma, tol, max_iter)
}

#' Sample medians for vs-ref PH model (C++ implementation)
#'
#' End-to-end posterior sampler for proportional hazards model.
#' Samples log-HR from posterior, then baseline hazards, then computes medians.
#'
#' @param E_C Integer vector of control events per interval
#' @param PT_C Numeric vector of control person-time per interval
#' @param E_T Integer vector of treatment events per interval
#' @param PT_T Numeric vector of treatment person-time per interval
#' @param alpha_prior Numeric vector of Gamma prior shape parameters
#' @param beta_prior Numeric vector of Gamma prior rate parameters
#' @param interval_lengths Numeric vector of interval durations
#' @param mu Log-HR prior mean
#' @param sigma Log-HR prior SD
#' @param num_samples Number of posterior samples
#' @return List with "medCtrl", "medTrt", and "logHR" vectors
#' @export
sample_vs_ref_medians_ph_cpp <- function(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, mu, sigma, num_samples) {
    .Call(`_evolveTrial_sample_vs_ref_medians_ph_cpp`, E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, mu, sigma, num_samples)
}

#' Sample medians for vs-ref independent model (C++ implementation)
#'
#' End-to-end posterior sampler for independent hazards model.
#' Used for single-arm trials and multi-arm trials with independent hazards.
#'
#' @param E_C Integer vector of control events per interval
#' @param PT_C Numeric vector of control person-time per interval
#' @param E_T Integer vector of treatment events per interval
#' @param PT_T Numeric vector of treatment person-time per interval
#' @param alpha_prior Numeric vector of Gamma prior shape parameters
#' @param beta_prior Numeric vector of Gamma prior rate parameters
#' @param interval_lengths Numeric vector of interval durations
#' @param num_samples Number of posterior samples
#' @return List with "medCtrl" and "medTrt" vectors (no logHR for independent model)
#' @export
sample_vs_ref_medians_independent_cpp <- function(E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, num_samples) {
    .Call(`_evolveTrial_sample_vs_ref_medians_independent_cpp`, E_C, PT_C, E_T, PT_T, alpha_prior, beta_prior, interval_lengths, num_samples)
}

#' Test Rcpp setup
#'
#' Simple test function to verify Rcpp and RcppArmadillo are working.
#'
#' @param x A numeric vector
#' @return Sum of the vector
#' @export
test_rcpp_sum <- function(x) {
    .Call(`_evolveTrial_test_rcpp_sum`, x)
}

#' Test Armadillo matrix operations
#'
#' @param n Matrix dimension
#' @return Mean of random normal matrix
#' @export
test_armadillo_random <- function(n) {
    .Call(`_evolveTrial_test_armadillo_random`, n)
}

